const PETS = [
  {
    "name": "우리",
    "elements": "지8 수2",
    "passive": "치유",
    "grade": "일반",
    "category": "두리류",
    "img": "assets/10.webp",
    "hp": 17.85,
    "atk": 2.55,
    "def": 2.47,
    "spd": 2.62,
    "element": "지"
  },
  {
    "name": "카우[還]",
    "elements": "지7 풍3",
    "passive": "불굴의 의지",
    "grade": "일반",
    "category": "카쿠류",
    "img": "assets/331.webp",
    "hp": 31.22,
    "atk": 6.38,
    "def": 6.41,
    "spd": 5.61,
    "element": "지"
  },
  {
    "name": "바쿠",
    "elements": "지9 수1",
    "passive": "불굴의 의지",
    "grade": "일반",
    "category": "카쿠류",
    "img": "assets/328.webp",
    "hp": 40.06,
    "atk": 7.93,
    "def": 5.98,
    "spd": 5.8,
    "element": "지"
  },
  {
    "name": "초아란",
    "elements": "지8 풍2",
    "passive": "전투 집중",
    "grade": "일반",
    "category": "아마란류",
    "img": "assets/choaran-portrait.png",
    "hp": 42.9,
    "atk": 9.27,
    "def": 5.68,
    "spd": 5.67,
    "element": "지"
  },
  {
    "name": "아리노스",
    "elements": "지5 수5",
    "passive": "치유",
    "grade": "일반",
    "category": "스토라지류",
    "img": "assets/459.webp",
    "hp": 61.75,
    "atk": 10,
    "def": 9.77,
    "spd": 6.11,
    "element": "지"
  },
  {
    "name": "산타밤비",
    "elements": "지7 수3",
    "passive": "파열",
    "grade": "일반",
    "category": "밤미류",
    "img": "assets/722.webp",
    "hp": 52.92,
    "atk": 10.57,
    "def": 6.66,
    "spd": 9.35,
    "element": "지"
  },
  {
    "name": "호크곤",
    "elements": "지7 수3",
    "passive": "격노",
    "grade": "일반",
    "category": "네고스류",
    "img": "assets/247.webp",
    "hp": 55.84,
    "atk": 10.75,
    "def": 8.46,
    "spd": 5.14,
    "element": "지"
  },
  {
    "name": "어린백룡",
    "elements": "지8 수2",
    "passive": "전광석화",
    "grade": "일반",
    "category": "기타류",
    "img": "assets/a771.webp",
    "hp": 50.59,
    "atk": 11.49,
    "def": 6.18,
    "spd": 7.64,
    "element": "지"
  },
  {
    "name": "라이데슬라",
    "elements": "지5 풍5",
    "passive": "강철",
    "grade": "일반",
    "category": "기타류",
    "img": "assets/738.webp",
    "hp": 67.13,
    "atk": 11.93,
    "def": 12.66,
    "spd": 3.5,
    "element": "지"
  },
  {
    "name": "지룡",
    "elements": "지6 수4",
    "passive": "심장 관통",
    "grade": "일반",
    "category": "지룡류",
    "img": "assets/598.webp",
    "hp": 57.93,
    "atk": 12.39,
    "def": 8.35,
    "spd": 7.05,
    "element": "지"
  },
  {
    "name": "파사트",
    "elements": "지5 수5",
    "passive": "암살",
    "grade": "일반",
    "category": "심해류",
    "img": "assets/819.webp",
    "hp": 57.84,
    "atk": 12.77,
    "def": 7.89,
    "spd": 7.17,
    "element": "지"
  },
  {
    "name": "테라로스",
    "elements": "지8 수2",
    "passive": "폭주",
    "grade": "일반",
    "category": "메가류",
    "img": "assets/699.webp",
    "hp": 68.61,
    "atk": 14.26,
    "def": 12.24,
    "spd": 6.75,
    "element": "지"
  },
  {
    "name": "펜타스",
    "elements": "지2 수8",
    "passive": "치유",
    "grade": "일반",
    "category": "펜타스 류",
    "img": "assets/345.webp",
    "hp": 31.92,
    "atk": 4.6,
    "def": 6.19,
    "spd": 2.48,
    "element": "수"
  },
  {
    "name": "사리온",
    "elements": "지2 수8",
    "passive": "투혼",
    "grade": "일반",
    "category": "아리온류",
    "img": "assets/801.webp",
    "hp": 37.96,
    "atk": 7.5,
    "def": 4.12,
    "spd": 6.45,
    "element": "수"
  },
  {
    "name": "아토라지[還]",
    "elements": "수10",
    "passive": "치유",
    "grade": "일반",
    "category": "스토라지류",
    "img": "assets/462.webp",
    "hp": 53.72,
    "atk": 8.69,
    "def": 7.67,
    "spd": 5.52,
    "element": "수"
  },
  {
    "name": "쿠보",
    "elements": "수5 화5",
    "passive": "심판",
    "grade": "상급",
    "category": "쿠보류",
    "img": "assets/311.webp",
    "hp": 51.13,
    "atk": 9.42,
    "def": 9.42,
    "spd": 5.38,
    "element": "수"
  },
  {
    "name": "은가로스",
    "elements": "지4 수6",
    "passive": "격노",
    "grade": "일반",
    "category": "모가로스류",
    "img": "assets/133.webp",
    "hp": 53.7,
    "atk": 10.26,
    "def": 8.58,
    "spd": 5.54,
    "element": "수"
  },
  {
    "name": "아누",
    "elements": "수5 화5",
    "passive": "광휘",
    "grade": "일반",
    "category": "카누류",
    "img": "assets/634.webp",
    "hp": 51.93,
    "atk": 10.77,
    "def": 6.68,
    "spd": 8.95,
    "element": "수"
  },
  {
    "name": "테라비스",
    "elements": "수10",
    "passive": "폭주",
    "grade": "일반",
    "category": "메가류",
    "img": "assets/700.webp",
    "hp": 56.14,
    "atk": 11.26,
    "def": 6.9,
    "spd": 9.65,
    "element": "수"
  },
  {
    "name": "투이[還]",
    "elements": "수5 화5",
    "passive": "불굴의 의지",
    "grade": "상급",
    "category": "무이류",
    "img": "assets/384.webp",
    "hp": 64.51,
    "atk": 11.6,
    "def": 11.38,
    "spd": 3.36,
    "element": "수"
  },
  {
    "name": "기라노[還]",
    "elements": "수5 화5",
    "passive": "전투 집중",
    "grade": "일반",
    "category": "얀기로류",
    "img": "assets/862.webp",
    "hp": 53.88,
    "atk": 12,
    "def": 7.49,
    "spd": 6.05,
    "element": "수"
  },
  {
    "name": "부루마루",
    "elements": "수8 화2",
    "passive": "에니키의 축복",
    "grade": "일반",
    "category": "구루마루류",
    "img": "assets/525.webp",
    "hp": 59.72,
    "atk": 12.5,
    "def": 7.25,
    "spd": 9.49,
    "element": "수"
  },
  {
    "name": "청주작[還]",
    "elements": "수9 화1",
    "passive": "청영의 화조",
    "grade": "일반",
    "category": "사신(四神)류",
    "img": "assets/827.webp",
    "hp": 60.67,
    "atk": 12.9,
    "def": 7.06,
    "spd": 9.42,
    "element": "수"
  },
  {
    "name": "테이토스[進]",
    "elements": "수5 화5",
    "passive": "격노",
    "grade": "일반",
    "category": "프리카토스류",
    "img": "assets/397.webp",
    "hp": 78.43,
    "atk": 14.76,
    "def": 14.11,
    "spd": 3.42,
    "element": "수"
  },
  {
    "name": "불그리",
    "elements": "화7 풍3",
    "passive": "미정",
    "grade": "상급",
    "category": "두리류",
    "img": "assets/5.webp",
    "hp": 21.04,
    "atk": 3.5,
    "def": 3.1,
    "spd": 3.9,
    "element": "화"
  },
  {
    "name": "바카우",
    "elements": "화6 풍4",
    "passive": "불굴의 의지",
    "grade": "일반",
    "category": "카쿠류",
    "img": "assets/327.webp",
    "hp": 37.3,
    "atk": 7.48,
    "def": 5.71,
    "spd": 6.45,
    "element": "화"
  },
  {
    "name": "베로포리[還]",
    "elements": "수3 화7",
    "passive": "불굴의 의지",
    "grade": "일반",
    "category": "베론류",
    "img": "assets/216.webp",
    "hp": 57.22,
    "atk": 9.18,
    "def": 11.14,
    "spd": 4.81,
    "element": "화"
  },
  {
    "name": "노라돈",
    "elements": "화8 풍2",
    "passive": "강철",
    "grade": "일반",
    "category": "고르돈류",
    "img": "assets/301.webp",
    "hp": 49.02,
    "atk": 10.22,
    "def": 7.31,
    "spd": 6.15,
    "element": "화"
  },
  {
    "name": "페루루[還]",
    "elements": "화5 풍5",
    "passive": "심장 관통",
    "grade": "일반",
    "category": "베르가류",
    "img": "assets/856.webp",
    "hp": 49.98,
    "atk": 10.81,
    "def": 6.28,
    "spd": 8.49,
    "element": "화"
  },
  {
    "name": "라디나",
    "elements": "화7 풍3",
    "passive": "조준",
    "grade": "일반",
    "category": "기타류",
    "img": "assets/737.webp",
    "hp": 50.14,
    "atk": 11.27,
    "def": 6.47,
    "spd": 7.38,
    "element": "화"
  },
  {
    "name": "호크",
    "elements": "화5 풍5",
    "passive": "전광 석화",
    "grade": "일반",
    "category": "호크류",
    "img": "assets/680.webp",
    "hp": 54.13,
    "atk": 11.87,
    "def": 6.27,
    "spd": 9.51,
    "element": "화"
  },
  {
    "name": "레피온",
    "elements": "수2 화8",
    "passive": "심장 관통",
    "grade": "일반",
    "category": "샤베르류",
    "img": "assets/665.webp",
    "hp": 54.24,
    "atk": 12.3,
    "def": 6.83,
    "spd": 8.57,
    "element": "화"
  },
  {
    "name": "가론고르",
    "elements": "수2 화8",
    "passive": "조준",
    "grade": "일반",
    "category": "고르돈류",
    "img": "assets/290.webp",
    "hp": 58.79,
    "atk": 12.69,
    "def": 8.49,
    "spd": 6.04,
    "element": "화"
  },
  {
    "name": "바우트",
    "elements": "수1 화9",
    "passive": "강철",
    "grade": "일반",
    "category": "바우트류",
    "img": "assets/182.webp",
    "hp": 67.47,
    "atk": 13.02,
    "def": 12.47,
    "spd": 2,
    "element": "화"
  },
  {
    "name": "스피노[還]",
    "elements": "화10",
    "passive": "격노",
    "grade": "일반",
    "category": "스피노류",
    "img": "assets/838.webp",
    "hp": 58.01,
    "atk": 13.41,
    "def": 7.49,
    "spd": 7.34,
    "element": "화"
  },
  {
    "name": "레드드래곤[還]",
    "elements": "화9 풍1",
    "passive": "불타는 날개",
    "grade": "일반",
    "category": "드래곤류",
    "img": "assets/848.webp",
    "hp": 59.77,
    "atk": 14.4,
    "def": 7.9,
    "spd": 8.55,
    "element": "화"
  },
  {
    "name": "푸푸",
    "elements": "지3 풍7",
    "passive": "신속",
    "grade": "일반",
    "category": "우푸류",
    "img": "assets/54.webp",
    "hp": 21.3,
    "atk": 3.88,
    "def": 2.48,
    "spd": 4.86,
    "element": "풍"
  },
  {
    "name": "케이비[還]",
    "elements": "지2 풍8",
    "passive": "심판",
    "grade": "일반",
    "category": "큐이류",
    "img": "assets/286.webp",
    "hp": 34.59,
    "atk": 6.61,
    "def": 6.61,
    "spd": 7.19,
    "element": "풍"
  },
  {
    "name": "미도미도",
    "elements": "화2 풍8",
    "passive": "심장 관통",
    "grade": "일반",
    "category": "미도미도류",
    "img": "assets/608.webp",
    "hp": 42.4,
    "atk": 8.28,
    "def": 4.68,
    "spd": 7.93,
    "element": "풍"
  },
  {
    "name": "쿠팡",
    "elements": "화3 풍7",
    "passive": "불굴의 의지",
    "grade": "일반",
    "category": "쿠아류",
    "img": "assets/512.webp",
    "hp": 42.02,
    "atk": 9.17,
    "def": 4.63,
    "spd": 6.97,
    "element": "풍"
  },
  {
    "name": "헷지",
    "elements": "풍10",
    "passive": "강철",
    "grade": "일반",
    "category": "기타류",
    "img": "assets/a796.webp",
    "hp": 51.93,
    "atk": 10.23,
    "def": 8.18,
    "spd": 4.86,
    "element": "풍"
  },
  {
    "name": "바쿠이노",
    "elements": "화3 풍7",
    "passive": "심판",
    "grade": "일반",
    "category": "볼케이노류",
    "img": "assets/644.webp",
    "hp": 50.25,
    "atk": 10.58,
    "def": 7.17,
    "spd": 6.4,
    "element": "풍"
  },
  {
    "name": "골드테라곤",
    "elements": "지2 풍8",
    "passive": "잔상",
    "grade": "일반",
    "category": "도라비스류",
    "img": "assets/420.webp",
    "hp": 51.52,
    "atk": 10.94,
    "def": 6.62,
    "spd": 9.09,
    "element": "풍"
  },
  {
    "name": "엘노스",
    "elements": "화1 풍9",
    "passive": "광휘",
    "grade": "일반",
    "category": "불카노스류",
    "img": "assets/563.webp",
    "hp": 50.55,
    "atk": 11.31,
    "def": 6.47,
    "spd": 7.47,
    "element": "풍"
  },
  {
    "name": "흑갈푸스",
    "elements": "화4 풍6",
    "passive": "투혼",
    "grade": "일반",
    "category": "갈푸스류",
    "img": "assets/174.webp",
    "hp": 54.91,
    "atk": 11.93,
    "def": 6.67,
    "spd": 9.16,
    "element": "풍"
  },
  {
    "name": "엘피노",
    "elements": "화2 풍8",
    "passive": "격노",
    "grade": "일반",
    "category": "스피노류",
    "img": "assets/517.webp",
    "hp": 53.7,
    "atk": 12.27,
    "def": 7.56,
    "spd": 6.47,
    "element": "풍"
  },
  {
    "name": "고르돈[融](풍)",
    "elements": "풍10",
    "passive": "기동 코어",
    "grade": "일반",
    "category": "합성펫류",
    "img": "assets/946.webp",
    "hp": 58.39,
    "atk": 12.96,
    "def": 8.92,
    "spd": 6.36,
    "element": "풍"
  },
  {
    "name": "황룡[還]",
    "elements": "화1 풍9",
    "passive": "광휘의 권능",
    "grade": "일반",
    "category": "사신(四神)류",
    "img": "assets/831.webp",
    "hp": 59.49,
    "atk": 13.53,
    "def": 7.72,
    "spd": 8.45,
    "element": "풍"
  }
];
